:scheduler:
  :schedule:
    balance_user_mail_job:
      cron: "0 2 1 * *"
      class: BalanceUserMailJob
    notify_expense_expiring_job:
      cron: "0 8 * * *"
      class: NotifyExpenseExpiringJob
    notify_month_begin_job:
      cron: "0 8 1 * *"
      class: NotifyMonthBeginJob
    notify_friday_job:
      cron: "0 17 * * 5"
      class: NotifyFridayJob
    notify_monday_job:
      cron: "0 8 * * 1"
      class: NotifyMondayJob
