:scheduler:
  :schedule:
    balance_user_mail_job:
      cron: "0 2 1 * *"
      class: BalanceUserMailJob
    notify_expense_expiring_job:
      cron: "0 8 * * *"
      class: NotifyExpenseExpiringJob
