module CategoriesHelper
  def all_available_icons
    %w[
      fa-question-circle
      fa-ambulance
      fa-baby-carriage
      fa-balance-scale
      fa-birthday-cake
      fa-book
      fa-briefcase
      fa-bus
      fa-car
      fa-child
      fa-coffee
      fa-credit-card
      fa-cutlery
      fa-chart-line
      fa-film
      fa-graduation-cap
      fa-home
      fa-hospital
      fa-hotel
      fa-plane
      fa-shopping-cart
      fa-subway
      fa-taxi
      fa-train
      fa-university
      fa-user-md
      fa-users
      fa-wrench
      fa-gamepad
      fa-gift
      fa-music
      fa-heart
    ]
  end
end
